require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/LineLength:
  Max: 180

Metrics/ClassLength:
  Max: 200

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*'
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/defaults.rb'
    - 'lib/app/*'
    - 'db/migrate/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'app/controllers/**/*'
    - 'db/migrate/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Style/GuardClause:
  Enabled: false

RSpec/ExampleLength:
  Max: 30

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/acceptance/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/acceptance/**/*'
    - 'spec/requests/**/*'

RSpec/NestedGroups:
  Max: 7

RSpec/MultipleExpectations:
  Enabled: false
