version: '3'
services:
  db:
    image: postgres:11.1
    volumes:
      - ./docker/init.sh:/docker-entrypoint-initdb.d/init.sh
      - pg-data:/var/lib/postgresql/data

  app: &app
    image: startupcraftio/ruby-pg:2.7.0-11
    command: bash
    volumes:
      - .:/app
      - bundler-data:/usr/local/bundle/:cached
      - bin-data:/usr/local/bin/:cached
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
    depends_on:
      - db
      - redis

  api:
    <<: *app
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    environment:
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-0}
    ports:
      - "3001:3001"

  redis:
    image: redis:alpine

  sidekiq:
    <<: *app
    command: bundle exec sidekiq -C config/sidekiq.yml

  nginx:
    image: 'nginx'
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - './docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf'
    depends_on:
      - 'api'

volumes:
  bundler-data:
  bin-data:
  pg-data:
